name: Update Backend Version

on:
  repository_dispatch:
    types: [backend-release]
  workflow_dispatch:
    inputs:
      backend_version:
        description: 'Backend version (e.g., v0.2.3)'
        required: true
        type: string
      backend_sha256:
        description: 'SHA256 of the vendored archive'
        required: true
        type: string
      backend_commit:
        description: 'Git commit hash of the backend release'
        required: true
        type: string

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set version variables
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "BACKEND_VERSION=${{ github.event.inputs.backend_version }}" >> $GITHUB_ENV
          echo "BACKEND_SHA256=${{ github.event.inputs.backend_sha256 }}" >> $GITHUB_ENV
          echo "BACKEND_COMMIT=${{ github.event.inputs.backend_commit }}" >> $GITHUB_ENV
        else
          echo "BACKEND_VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_ENV
          echo "BACKEND_SHA256=${{ github.event.client_payload.sha256 }}" >> $GITHUB_ENV
          echo "BACKEND_COMMIT=${{ github.event.client_payload.commit }}" >> $GITHUB_ENV
        fi
        
    - name: Update Flatpak manifest
      run: |
        # Update the backend version, SHA256, and commit in the manifest
        sed -i "s|tag: v[0-9]\+\.[0-9]\+\.[0-9]\+|tag: ${BACKEND_VERSION}|g" io.github.tobagin.Karere.yml
        sed -i "s|commit: [a-f0-9]\{40\}|commit: ${BACKEND_COMMIT}|g" io.github.tobagin.Karere.yml
        sed -i "s|karere-backend-node-modules-v[0-9]\+\.[0-9]\+\.[0-9]\+\.tar\.gz|karere-backend-node-modules-${BACKEND_VERSION}.tar.gz|g" io.github.tobagin.Karere.yml
        sed -i "s|sha256: [a-f0-9]\{64\}|sha256: ${BACKEND_SHA256}|g" io.github.tobagin.Karere.yml
        
        echo "Updated manifest with:"
        echo "- Version: ${BACKEND_VERSION}"
        echo "- SHA256: ${BACKEND_SHA256}"
        echo "- Commit: ${BACKEND_COMMIT}"
        
    - name: Verify changes
      run: |
        echo "## Changes made to io.github.tobagin.Karere.yml:" >> $GITHUB_STEP_SUMMARY
        echo '```diff' >> $GITHUB_STEP_SUMMARY
        git diff io.github.tobagin.Karere.yml >> $GITHUB_STEP_SUMMARY || echo "No changes detected" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update backend to ${{ env.BACKEND_VERSION }}"
        title: "Update Karere Backend to ${{ env.BACKEND_VERSION }}"
        body: |
          ## 🚀 Backend Update
          
          This PR updates the Karere Backend to version **${{ env.BACKEND_VERSION }}**.
          
          ### Changes:
          - Updated backend version tag to `${{ env.BACKEND_VERSION }}`
          - Updated commit hash to `${{ env.BACKEND_COMMIT }}`
          - Updated vendored dependencies SHA256 to `${{ env.BACKEND_SHA256 }}`
          
          ### Testing:
          ```bash
          flatpak-builder --force-clean builddir io.github.tobagin.Karere.yml
          flatpak run io.github.tobagin.Karere
          ```
          
          Auto-generated by GitHub Actions.
        branch: update-backend-${{ env.BACKEND_VERSION }}
        delete-branch: true
